'use client';
import { FormEvent, useState } from 'react';
import Link from 'next/link';
import { MessageSquareText, Send, ShieldCheck } from 'lucide-react';
import { apiFetch } from '@/lib/auth/apiFetch';
export default function StudentChatPage() {
 const [question,setQuestion]=useState(''); const [answer,setAnswer]=useState<any>(null); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
 const ask=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const res=await apiFetch('/api/student/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question})});const body=await res.json();if(!res.ok)throw new Error(body.error);setAnswer(body);}catch(cause:any){setError(cause.message)}finally{setBusy(false)}};
 return <main className="min-h-screen bg-slate-50 p-5"><div className="mx-auto max-w-4xl"><Link href="/student" className="text-xs font-bold text-slate-600">← Student portal</Link><section className="mt-5 rounded-2xl border bg-white p-6 shadow-sm"><p className="flex items-center gap-2 text-xs font-mono font-bold text-emerald-700"><ShieldCheck className="w-4" />GROUNDED COURSE CHAT</p><h1 className="mt-2 text-2xl font-extrabold">Ask your assigned notes</h1><p className="mt-1 text-sm text-slate-500">Answers only use PDF/PPT chunks attached to assessment rooms you joined. If the evidence is absent, the assistant refuses to guess.</p><form onSubmit={ask} className="mt-5 flex gap-2"><input value={question} onChange={e=>setQuestion(e.target.value)} className="flex-1 rounded-xl border px-4 py-3" placeholder="Ask a theory question…"/><button disabled={busy||!question.trim()} className="btn-primary px-4"><Send className="w-4" /></button></form>{error&&<p className="mt-3 rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}{answer&&<div className="mt-5 space-y-3"><div className="rounded-xl bg-slate-100 p-4 whitespace-pre-wrap text-sm">{answer.answer}</div>{answer.citations.map((citation:any,index:number)=><article key={index} className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm"><div className="flex gap-2 font-bold text-emerald-900"><MessageSquareText className="w-4" />{citation.documentTitle} · {citation.sourceLabel}</div><p className="mt-2 text-emerald-950/75">“{citation.excerpt}”</p></article>)}</div>}</section></div></main>;
}
