'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { FileText, PlusCircle, Radio, RefreshCw } from 'lucide-react';
import { apiFetch } from '@/lib/auth/apiFetch';
export default function TeacherDashboardPage() {
 const [items,setItems]=useState<any[]>([]); const [loading,setLoading]=useState(true);
 useEffect(()=>{apiFetch('/api/assessments').then(r=>r.json()).then(body=>setItems(body.assessments||[])).finally(()=>setLoading(false));},[]);
 return <main className="space-y-7"><div className="flex items-center justify-between border-b pb-5"><div><p className="text-xs font-mono font-bold text-emerald-700">PRIVATE FACULTY WORKSPACE</p><h1 className="mt-1 text-3xl font-extrabold">Your assessments</h1><p className="mt-1 text-sm text-slate-500">Only assessments and documents uploaded by your signed-in account appear here.</p></div><Link href="/teacher/create" className="btn-primary"><PlusCircle className="w-4" />Create assessment</Link></div>{loading?<div className="flex gap-2 text-sm text-slate-500"><RefreshCw className="w-4 animate-spin"/>Loading your workspace…</div>:items.length?<div className="grid gap-4">{items.map(item=><article key={item.id} className="rounded-xl border bg-white p-5"><div className="flex items-center justify-between gap-4"><div className="flex items-center gap-3"><Radio className="w-5 text-emerald-600"/><div><p className="font-bold">{item.title}</p><p className="text-xs text-slate-500">{item.moduleName} · {item.totalQuestions} questions · Room {item.roomCode || 'not created'}</p></div></div><div className="flex gap-2"><Link href={`/teacher/results/${item.id}`} className="rounded-lg border px-3 py-2 text-xs font-bold">Results & analytics</Link>{item.roomCode&&<Link href={`/teacher/rooms/${item.roomCode}`} className="rounded-lg bg-slate-900 px-3 py-2 text-xs font-bold text-white">Open room</Link>}</div></div></article>)}</div>:<section className="rounded-2xl border border-dashed bg-white p-12 text-center"><FileText className="mx-auto w-8 text-slate-400"/><h2 className="mt-3 font-bold">No assessments yet</h2><p className="mt-1 text-sm text-slate-500">Upload your own PDF or PPT, then create your first assessment.</p><Link href="/teacher/materials" className="mt-5 inline-flex text-sm font-bold text-emerald-700">Open my materials →</Link></section>}</main>;
}
