'use client';
import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { FileText, Pencil, PlusCircle, Radio, RefreshCw, Trash2, Users } from 'lucide-react';
import { apiFetch } from '@/lib/auth/apiFetch';

const statusStyle: Record<string, string> = { ACTIVE: 'bg-emerald-100 text-emerald-800 border-emerald-200', WAITING: 'bg-amber-100 text-amber-800 border-amber-200', COMPLETED: 'bg-slate-100 text-slate-700 border-slate-200', EXPIRED: 'bg-rose-100 text-rose-800 border-rose-200' };

export default function TeacherDashboardPage() {
  const [items, setItems] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [account, setAccount] = useState<any>(null);
  const load = useCallback(async () => { setError(''); try { const response = await apiFetch('/api/assessments'); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Could not load rooms.'); setItems(body.assessments || []); setAccount(body.account || null); } catch (cause: any) { setError(cause.message || 'Could not load rooms.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const editRoom = async (code: string) => { const newCode = window.prompt('New room code (4–10 letters/numbers):', code); if (!newCode || newCode.trim().toUpperCase() === code) return; const response = await apiFetch(`/api/rooms/${code}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ code: newCode }) }); const body = await response.json(); if (!response.ok) return setError(body.error || 'Could not update room.'); void load(); };
  const changeStatus = async (code: string, status: string) => { const response = await apiFetch(`/api/rooms/${code}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status }) }); const body = await response.json(); if (!response.ok) return setError(body.error || 'Could not update room.'); void load(); };
  const deleteRoom = async (code: string) => { if (!window.confirm(`Delete room ${code}? Rooms with student attempts cannot be deleted.`)) return; const response = await apiFetch(`/api/rooms/${code}`, { method: 'DELETE' }); const body = await response.json(); if (!response.ok) return setError(body.error || 'Could not delete room.'); void load(); };
  const rooms = items.flatMap(item => (item.rooms || []).map((room: any) => ({ ...room, assessment: item }))); const liveRooms = rooms.filter((room: any) => room.status === 'ACTIVE');
  return <main className="space-y-7"><div className="flex flex-col justify-between gap-4 border-b pb-5 sm:flex-row sm:items-center"><div><p className="text-xs font-mono font-bold text-emerald-700">PRIVATE FACULTY WORKSPACE</p><h1 className="mt-1 text-3xl font-extrabold">Assessments & live rooms</h1><p className="mt-1 text-sm text-slate-500">Only rooms and materials created by your signed-in faculty account appear here.</p></div><div className="flex gap-2"><button onClick={() => { setLoading(true); void load(); }} className="rounded-lg border px-3 py-2 text-xs font-bold"><RefreshCw className="inline w-3.5" /> Refresh</button><Link href="/teacher/create" className="btn-primary"><PlusCircle className="w-4" />Create assessment</Link></div></div>{error && <p className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{error}</p>}{loading ? <div className="flex gap-2 text-sm text-slate-500"><RefreshCw className="w-4 animate-spin" />Loading your workspace…</div> : <><section><div className="mb-3 flex items-center gap-2"><Radio className="w-5 text-emerald-600" /><h2 className="font-bold">Live now ({liveRooms.length})</h2></div>{liveRooms.length ? <div className="grid gap-3 md:grid-cols-2">{liveRooms.map((room: any) => <RoomCard key={room.id} room={room} edit={editRoom} update={changeStatus} remove={deleteRoom} />)}</div> : <div className="rounded-xl border border-dashed bg-white p-5 text-sm text-slate-500">No live rooms right now. Start a waiting room when you are ready for students to join.</div>}</section><section><h2 className="mb-3 font-bold">All your rooms</h2>{rooms.length ? <div className="grid gap-3">{rooms.filter((room: any) => room.status !== 'ACTIVE').map((room: any) => <RoomCard key={room.id} room={room} edit={editRoom} update={changeStatus} remove={deleteRoom} />)}</div> : <section className="rounded-2xl border border-dashed bg-white p-12 text-center"><FileText className="mx-auto w-8 text-slate-400" /><h2 className="mt-3 font-bold">No rooms yet</h2><p className="mt-1 text-sm text-slate-500">Upload your own PDF or PPT, then create an assessment and publish a room.</p><Link href="/teacher/materials" className="mt-5 inline-flex text-sm font-bold text-emerald-700">Open my materials →</Link></section>}</section></>}</main>;
}

function RoomCard({ room, edit, update, remove }: any) { const assessment = room.assessment; return <article className="rounded-xl border bg-white p-5 shadow-sm"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><div className="flex items-center gap-2"><span className={`rounded-full border px-2 py-0.5 text-[11px] font-bold ${statusStyle[room.status] || statusStyle.WAITING}`}>{room.status}</span><span className="font-mono text-sm font-bold tracking-wider">{room.code}</span></div><p className="mt-3 font-bold">{assessment.title}</p><p className="mt-1 text-xs text-slate-500">{assessment.moduleName} · {assessment.totalQuestions} questions · {assessment.durationMinutes} min</p><p className="mt-3 flex items-center gap-1 text-xs font-semibold text-slate-600"><Users className="w-3.5" />{room.participantCount} student{room.participantCount === 1 ? '' : 's'} joined</p></div><div className="flex flex-wrap items-start gap-2"><Link href={`/teacher/rooms/${room.code}`} className="rounded-lg bg-slate-900 px-3 py-2 text-xs font-bold text-white">Open room</Link>{room.status === 'WAITING' && <button onClick={() => update(room.code, 'ACTIVE')} className="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-bold text-white">Start live</button>}{room.status === 'ACTIVE' && <button onClick={() => update(room.code, 'COMPLETED')} className="rounded-lg border border-amber-300 bg-amber-50 px-3 py-2 text-xs font-bold text-amber-800">End room</button>}<button onClick={() => edit(room.code)} className="rounded-lg border px-3 py-2 text-xs font-bold" title="Edit room code"><Pencil className="w-3.5" /></button><button onClick={() => remove(room.code)} className="rounded-lg border border-rose-200 px-3 py-2 text-xs font-bold text-rose-700" title="Delete empty room"><Trash2 className="w-3.5" /></button></div></div></article>; }
