'use client';

import { Suspense, useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { createUserWithEmailAndPassword, GoogleAuthProvider, signInWithEmailAndPassword, signInWithPopup, updateProfile } from 'firebase/auth';
import { ArrowRight, GraduationCap, ShieldCheck, UserRound } from 'lucide-react';
import { firebaseAuth } from '@/lib/firebase/client';

function AuthForm() {
  const router = useRouter(); const search = useSearchParams();
  const [mode, setMode] = useState<'signin' | 'signup'>('signin');
  const [role, setRole] = useState<'faculty' | 'student'>(search.get('role') === 'student' ? 'student' : 'faculty');
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { if (mode === 'signup') { const credential = await createUserWithEmailAndPassword(firebaseAuth, email, password); if (name.trim()) await updateProfile(credential.user, { displayName: name.trim() }); } else await signInWithEmailAndPassword(firebaseAuth, email, password); router.replace(search.get('next') || (role === 'faculty' ? '/teacher/dashboard' : '/student')); } catch (cause: any) { setError((cause?.message || 'Authentication failed').replace('Firebase: ', '')); } finally { setBusy(false); } };
  const google = async () => { setBusy(true); setError(''); try { await signInWithPopup(firebaseAuth, new GoogleAuthProvider()); router.replace(search.get('next') || (role === 'faculty' ? '/teacher/dashboard' : '/student')); } catch (cause: any) { setError((cause?.message || 'Google sign-in failed').replace('Firebase: ', '')); } finally { setBusy(false); } };
  return <main className="min-h-screen grid place-items-center bg-[#F8FAFC] p-4"><form onSubmit={submit} className="w-full max-w-md rounded-2xl border border-slate-200 bg-white p-7 shadow-card space-y-4"><div className="grid grid-cols-2 rounded-xl bg-slate-100 p-1"><button type="button" onClick={() => setRole('student')} className={`rounded-lg py-2 text-xs font-bold ${role === 'student' ? 'bg-white shadow-sm' : 'text-slate-500'}`}><GraduationCap className="mr-1 inline w-4" />Student</button><button type="button" onClick={() => setRole('faculty')} className={`rounded-lg py-2 text-xs font-bold ${role === 'faculty' ? 'bg-white shadow-sm' : 'text-slate-500'}`}><UserRound className="mr-1 inline w-4" />Faculty</button></div><div><p className="text-xs font-mono font-bold uppercase text-[#3F6B5B]">Firebase-secured access</p><h1 className="mt-1 text-2xl font-extrabold">{mode === 'signin' ? 'Welcome back' : 'Create your account'}</h1></div><button type="button" disabled={busy} onClick={google} className="w-full rounded-xl border border-slate-300 bg-white py-3 text-sm font-bold text-slate-800 hover:bg-slate-50">Continue with Google</button><div className="flex items-center gap-3 text-[11px] text-slate-400"><span className="h-px flex-1 bg-slate-200" />or use email<span className="h-px flex-1 bg-slate-200" /></div>{mode === 'signup' && <input required value={name} onChange={e => setName(e.target.value)} className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm" placeholder="Full name" />}<input required type="email" value={email} onChange={e => setEmail(e.target.value)} className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm" placeholder="Email address"/><input required minLength={6} type="password" value={password} onChange={e => setPassword(e.target.value)} className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm" placeholder="Password (minimum 6 characters)"/>{error && <p className="rounded-lg bg-rose-50 p-3 text-xs text-rose-700">{error}</p>}<button disabled={busy} className="btn-primary w-full justify-center py-3">{busy ? 'Please wait…' : mode === 'signin' ? 'Sign in securely' : 'Create account'}<ArrowRight className="w-4" /></button><button type="button" onClick={() => setMode(mode === 'signin' ? 'signup' : 'signin')} className="w-full text-xs font-bold text-slate-600">{mode === 'signin' ? 'New here? Create an account' : 'Already have an account? Sign in'}</button><p className="flex justify-center gap-1 text-center text-[11px] text-slate-500"><ShieldCheck className="w-3.5" />Real Firebase Authentication</p></form></main>;
}
export default function AuthPage() { return <Suspense fallback={<main className="min-h-screen bg-[#F8FAFC]" />}><AuthForm /></Suspense>; }
