'use client';

import { FormEvent, useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowRight, BookOpen, History, MessageSquareText, PlusCircle, RefreshCw } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { apiFetch } from '@/lib/auth/apiFetch';

export default function StudentPortalPage() {
  const [code, setCode] = useState(''); const [history, setHistory] = useState<any[]>([]); const [loading, setLoading] = useState(true);
  const router = useRouter();
  const load = () => { setLoading(true); apiFetch('/api/student/history').then(r => r.ok ? r.json() : { history: [] }).then(data => setHistory(data.history || [])).catch(() => setHistory([])).finally(() => setLoading(false)); };
  useEffect(() => { load(); }, []);
  const submit = (event: FormEvent) => { event.preventDefault(); if (/^[A-Z0-9]{6}$/i.test(code)) router.push(`/exam/${code.toUpperCase()}`); };
  const completed = history.filter(item => item.status === 'COMPLETED' || item.status === 'AUTO_SUBMITTED');
  return <main className="space-y-7"><div className="flex flex-col justify-between gap-4 border-b pb-5 sm:flex-row sm:items-center"><div><p className="text-xs font-mono font-bold text-emerald-700">STUDENT WORKSPACE</p><h1 className="mt-1 text-3xl font-extrabold">Your quizzes and study material</h1><p className="mt-1 text-sm text-slate-500">Join a room shared by your faculty, review completed quizzes, or study from your assigned notes.</p></div><button onClick={load} className="rounded-lg border px-3 py-2 text-xs font-bold"><RefreshCw className={`mr-1 inline w-3.5 ${loading ? 'animate-spin' : ''}`} />Refresh</button></div>
    <div className="grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><section className="rounded-xl border bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-lg bg-[#EEF3F8] text-[#17324D]"><PlusCircle className="w-5" /></div><div><p className="text-xs font-mono text-slate-500">ASSESSMENT ACCESS</p><h2 className="font-bold">Join a faculty room</h2></div></div><p className="mt-4 text-sm text-slate-500">Enter the six-character code shared by your professor to start an available assessment.</p><form onSubmit={submit} className="mt-5 flex gap-2"><input value={code} onChange={event => setCode(event.target.value.toUpperCase().replace(/[^A-Z0-9]/g, '').slice(0, 6))} className="min-w-0 flex-1 rounded-lg border bg-slate-50 px-4 py-3 font-mono font-bold tracking-[0.18em] outline-none focus:border-[#17324D]" placeholder="ROOM CODE"/><button disabled={!/^[A-Z0-9]{6}$/.test(code)} className="btn-primary px-4"><ArrowRight className="w-4" /></button></form></section><section className="rounded-xl border bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-lg bg-[#EEF5F2] text-[#3F6B5B]"><MessageSquareText className="w-5" /></div><div><p className="text-xs font-mono text-slate-500">MATERIAL HELP</p><h2 className="font-bold">Ask assigned notes</h2></div></div><p className="mt-4 text-sm text-slate-500">Ask questions from course material made available through your joined rooms. Each answer includes its source page.</p><Link href="/student/chat" className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-[#17324D]">Open study chat <ArrowRight className="w-4" /></Link></section></div>
    <section><div className="mb-3 flex items-center justify-between"><div><p className="text-xs font-mono text-slate-500">YOUR PROGRESS</p><h2 className="mt-1 text-xl font-bold">Past quizzes</h2></div><Link href="/student/history" className="text-sm font-bold text-[#17324D]">View all →</Link></div>{loading ? <div className="flex gap-2 rounded-xl border bg-white p-5 text-sm text-slate-500"><RefreshCw className="w-4 animate-spin" />Loading your quiz history…</div> : completed.length ? <div className="grid gap-3 md:grid-cols-3">{completed.slice(0, 3).map(item => <Link key={item.id} href={`/exam/${item.roomCode}/result`} className="rounded-xl border bg-white p-5 shadow-sm transition hover:border-[#C8D8E8]"><div className="flex items-start justify-between"><BookOpen className="w-5 text-[#17324D]"/><span className="rounded bg-[#EEF5F2] px-2 py-1 text-xs font-bold text-[#3F6B5B]">{item.score}%</span></div><p className="mt-4 text-sm font-bold">{item.title}</p><p className="mt-1 text-xs text-slate-500">{new Date(item.startedAt).toLocaleDateString()}</p></Link>)}</div> : <div className="rounded-xl border border-dashed bg-white p-8 text-center"><History className="mx-auto w-6 text-slate-400"/><p className="mt-2 text-sm font-bold">No completed quizzes yet</p><p className="mt-1 text-xs text-slate-500">Your completed assessments will appear here.</p></div>}</section>
  </main>;
}
